export const PACKAGE_LIST_REQUEST = 'PACKAGE_LIST_REQUEST'
export const PACKAGE_LIST_SUCCESS = 'PACKAGE_LIST_SUCCESS'
export const PACKAGE_LIST_FAIL = 'PACKAGE_LIST_FAIL'

export const PACKAGE_CREATE_REQUEST = 'PACKAGE_CREATE_REQUEST'
export const PACKAGE_CREATE_SUCCESS = 'PACKAGE_CREATE_SUCCESS'
export const PACKAGE_CREATE_FAIL = 'PACKAGE_CREATE_FAIL'
export const PACKAGE_CREATE_RESET = 'PACKAGE_CREATE_RESET'


export const CLIENT_LIST_REQUEST = 'CLIENT_LIST_REQUEST'
export const CLIENT_LIST_SUCCESS = 'CLIENT_LIST_SUCCESS'
export const CLIENT_LIST_FAIL = 'CLIENT_LIST_FAIL'
export const CLIENT_LIST_RESET = 'CLIENT_LIST_RESET'


export const CLIENT_CREATE_REQUEST = 'CLIENT_CREATE_REQUEST'
export const CLIENT_CREATE_SUCCESS = 'CLIENT_CREATE_SUCCESS'
export const CLIENT_CREATE_FAIL = 'CLIENT_CREATE_FAIL'
export const CLIENT_CREATE_RESET = 'CLIENT_CREATE_RESET'