export const SALE_CREATE_REQUEST = 'SALE_CREATE_REQUEST'
export const SALE_CREATE_SUCCESS = 'SALE_CREATE_SUCCESS'
export const SALE_CREATE_FAIL = 'SALE_CREATE_FAIL'
export const SALE_CREATE_RESET = 'SALE_CREATE_RESET'

export const SALE_DETAILS_REQUEST = 'SALE_DETAILS_REQUEST'
export const SALE_DETAILS_SUCCESS = 'SALE_DETAILS_SUCCESS'
export const SALE_DETAILS_FAIL = 'SALE_DETAILS_FAIL'

export const SALE_LIST_MY_REQUEST = 'SALE_LIST_MY_REQUEST'
export const SALE_LIST_MY_SUCCESS = 'SALE_LIST_MY_SUCCESS'
export const SALE_LIST_MY_FAIL = 'SALE_LIST_MY_FAIL'
export const SALE_LIST_MY_RESET = 'SALE_LIST_MY_RESET'

export const SALE_LIST_REQUEST = 'SALE_LIST_REQUEST'
export const SALE_LIST_SUCCESS = 'SALE_LIST_SUCCESS'
export const SALE_LIST_FAIL = 'SALE_LIST_FAIL'

export const SALE_DELETE_REQUEST = 'SALE_DELETE_REQUEST'
export const SALE_DELETE_SUCCESS = 'SALE_DELETE_SUCCESS'
export const SALE_DELETE_FAIL = 'SALE_DELETE_FAIL'
export const SALE_DELETE_RESET = 'SALE_DELETE_RESET'

export const SALE_UPDATE_REQUEST = 'SALE_UPDATE_REQUEST'
export const SALE_UPDATE_SUCCESS = 'SALE_UPDATE_SUCCESS'
export const SALE_UPDATE_FAIL = 'SALE_UPDATE_FAIL'
export const SALE_UPDATE_RESET = 'SALE_UPDATE_RESET'

export const SALE_SUBMIT_REQUEST = 'SALE_SUBMIT_REQUEST'
export const SALE_SUBMIT_SUCCESS = 'SALE_SUBMIT_SUCCESS'
export const SALE_SUBMIT_FAIL = 'SALE_SUBMIT_FAIL'
export const SALE_SUBMIT_RESET = 'SALE_SUBMIT_RESET'